services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 ghostsec.wsgi:application
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    environment:
      - DEBUG=0
      - POSTGRES_DB=ghostsec
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    networks:
      - ghostsec_network

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ghostsec
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - ghostsec_network

  redis:
    image: redis:6
    networks:
      - ghostsec_network

  nginx:
    image: nginx:1.19
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - ghostsec_network

networks:
  ghostsec_network:
    driver: bridge

volumes:
  postgres_data:
  static_volume:
  media_volume:
